name: flutter_food
description: A new Flutter project

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.0.0
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/images/IconoFIP.png  # AsegÃºrate de que esta ruta sea correcta
  uses-material-design: true
